name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      issues: write
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Download dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Display coverage
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage.xml
